name: Deploy Logger Function

on:
  push:
    branches:
      - "main"
    paths:
      - "scr/functions/**"
      - ".github/workflows/function.yml"
  workflow_dispatch:

env:
  AZURE_FUNCTION_PACKAGE_PATH: 'src/functions'  
  DOTNET_VERSION: '3.1.407'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Install Bicep
      run: |     
        $installPath = "$env:USERPROFILE\.bicep"
        $installDir = New-Item -ItemType Directory -Path $installPath -Force
        $installDir.Attributes += 'Hidden'
        (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")        
        $currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
        if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
        if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}         

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTION_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Azure Login
      uses: Azure/login@v1.1
      with:          
        creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
        enable-AzPSSession: false

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/output'
