name: Deploy infrastructure as code

on:
  push:
    branches:
      - "main"
    paths:
      - "bicep/**"
      - ".github/workflows/infra.yml"
    paths-ignore:
      - "bicep/event.bicep"
      - "bicep/modules/eventGrid/**"
  workflow_dispatch:          

env:
  RESOURCE_GROUP_NAME: eventgrid-demo-rg
  LOCATION: eastus

jobs:
  deploy_infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bicep
        run: |     
          curl -Lo download https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64          
          chmod +x ./download
          sudo mv ./download /usr/local/bin/bicep

      - name: Bicep Build
        run: |
          bicep build bicep/main.bicep

      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false

      - name: Create Resource Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}

      - name: Deploy Azure Resources
        id: deployInfra
        uses: Azure/arm-deploy@v1.0.1
        with:        
          scope: resourcegroup          
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          
          region: ${{ env.LOCATION }}        
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}        
          template: bicep/main.json   
          parameters: location=${{ env.LOCATION }} adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }}
          deploymentMode: Incremental

      - uses: gliech/create-github-secret-action@v1
        with:
          name: AZURE_FUNCTIONAPP_NAME
          value: ${{ steps.deployInfra.outputs.functionName }}
          pa_token: ${{ secrets.PA_TOKEN }}          
          
      - uses: gliech/create-github-secret-action@v1
        with:
          name: FUNCTION_NAME
          value: ${{ steps.deployInfra.outputs.functionName }}
          pa_token: ${{ secrets.PA_TOKEN }}       
          
      - uses: gliech/create-github-secret-action@v1
        with:
          name: FUNCTION_ID
          value: ${{ steps.deployInfra.outputs.functionId }}
          pa_token: ${{ secrets.PA_TOKEN }}      
          
      - uses: gliech/create-github-secret-action@v1
        with:
          name: STORAGE_ID
          value: ${{ steps.deployInfra.outputs.storageId }}
          pa_token: ${{ secrets.PA_TOKEN }}     
          
      - uses: gliech/create-github-secret-action@v1
        with:
          name: STORAGE_NAME
          value: ${{ steps.deployInfra.outputs.storageName }}
          pa_token: ${{ secrets.PA_TOKEN }}            
